#!/bin/sh
# Generated by agent-monitor. Do not edit.
set -u
PROVIDER="$1"                    # 'claude' | 'codex', baked at install time
EVENT="$2"                       # 'PreToolUse', 'Stop', ... baked per registration
MAX_PAYLOAD_BYTES=3072           # leaves room for envelope under PIPE_BUF-ish safety

TMP=$(mktemp 2>/dev/null) || exit 0
trap 'rm -f "$TMP"' EXIT
# Read stdin with a hard byte cap; strip newlines so we keep JSONL.
head -c $((MAX_PAYLOAD_BYTES + 1)) | tr -d '\n\r' > "$TMP" || exit 0
BYTES=$(wc -c < "$TMP")

# Extract session_id from the payload itself. Both Claude Code and Codex
# put `session_id` at the top level of their hook stdin payloads -- env
# vars are NOT reliable.
SESSION_ID=""
if command -v jq >/dev/null 2>&1; then
  SESSION_ID=$(jq -r '.session_id // .conversationId // .conversation_id // empty' "$TMP" 2>/dev/null) || SESSION_ID=""
fi
if [ -z "$SESSION_ID" ]; then
  # Fallback: small tolerant pattern. Real session_ids are UUIDs with no
  # quote escaping, so this works in practice.
  SESSION_ID=$(sed -n 's/.*"session_id":"\([^"]*\)".*/\1/p' "$TMP" | head -n1)
fi
if [ -z "$SESSION_ID" ]; then
  SESSION_ID=$(sed -n 's/.*"conversationId":"\([^"]*\)".*/\1/p' "$TMP" | head -n1)
fi
[ -z "$SESSION_ID" ] && SESSION_ID="unknown"

SESSION_HASH=$(printf '%s' "$SESSION_ID" | sha1sum | cut -c1-16)
SPOOL_DIR="$HOME/.local/state/agent-monitor/spool/$PROVIDER/$SESSION_HASH"
mkdir -p "$SPOOL_DIR" 2>/dev/null || exit 0
SPOOL="$SPOOL_DIR/$(date -u +%Y%m%d).jsonl"

TS_MS=$(date +%s%3N)

# M6: $PPID of the hook process is the agent CLI's PID (claude / codex). Used
# as liveness metadata on the sessions row. We also capture /proc stat field
# 22 (process starttime in clock ticks) so the UI can guard against PID reuse.
PARENT_PID="$PPID"
PARENT_STARTTIME_JSON="null"
if [ -r "/proc/$PARENT_PID/stat" ]; then
  PARENT_STAT=$(sed 's/^.*) //' "/proc/$PARENT_PID/stat" 2>/dev/null) || PARENT_STAT=""
  set -- $PARENT_STAT
  shift 19 2>/dev/null || true
  PARENT_STARTTIME="${1:-}"
  case "$PARENT_STARTTIME" in
    ''|*[!0-9]*) PARENT_STARTTIME_JSON="null" ;;
    *) PARENT_STARTTIME_JSON="$PARENT_STARTTIME" ;;
  esac
fi

if [ "$BYTES" -gt "$MAX_PAYLOAD_BYTES" ]; then
  PREFIX=$(head -c 128 "$TMP" | sed 's/"/\\"/g')
  printf '{"provider":"%s","event":"%s","session_id":"%s","observed_at_ms":%s,"payload_truncated":true,"payload_bytes":%s,"payload_prefix":"%s","parent_pid":%s,"parent_starttime":%s}\n' \
    "$PROVIDER" "$EVENT" "$SESSION_ID" "$TS_MS" "$BYTES" "$PREFIX" "$PARENT_PID" "$PARENT_STARTTIME_JSON" >> "$SPOOL" 2>/dev/null || true
else
  printf '{"provider":"%s","event":"%s","session_id":"%s","observed_at_ms":%s,"payload":%s,"parent_pid":%s,"parent_starttime":%s}\n' \
    "$PROVIDER" "$EVENT" "$SESSION_ID" "$TS_MS" "$(cat "$TMP")" "$PARENT_PID" "$PARENT_STARTTIME_JSON" >> "$SPOOL" 2>/dev/null || true
fi
exit 0
